name: Build winDialog

on:
  workflow_dispatch: # Manual Trigger
  # push:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish Single File Executable
      run: dotnet publish src/winDialog.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:Version="1.0.${{ github.run_number }}" -p:FileVersion="1.0.${{ github.run_number }}" -o ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: winDialog-exe
        path: ./publish/winDialog.exe
